// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwErSa50NF8ImSNyCSuwpJYQnp6J1mQ74',
    appId: '1:770206839151:web:a01fad13ae73531736789a',
    messagingSenderId: '770206839151',
    projectId: 'project-01-f644f',
    authDomain: 'project-01-f644f.firebaseapp.com',
    storageBucket: 'project-01-f644f.appspot.com',
    measurementId: 'G-VHRWK5NEWT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1SBrUXsjGngFDZqY69Q2ws1YmuZa1yHA',
    appId: '1:770206839151:android:4f6621f67f71b8a236789a',
    messagingSenderId: '770206839151',
    projectId: 'project-01-f644f',
    storageBucket: 'project-01-f644f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRonuppU5iXLd2NU-S24lhOVkWEhcaydY',
    appId: '1:770206839151:ios:bb492671f294f0c236789a',
    messagingSenderId: '770206839151',
    projectId: 'project-01-f644f',
    storageBucket: 'project-01-f644f.appspot.com',
    iosBundleId: 'com.example.app01',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRonuppU5iXLd2NU-S24lhOVkWEhcaydY',
    appId: '1:770206839151:ios:7531d2a24d743f7836789a',
    messagingSenderId: '770206839151',
    projectId: 'project-01-f644f',
    storageBucket: 'project-01-f644f.appspot.com',
    iosBundleId: 'com.example.app01.RunnerTests',
  );
}
